variable "domain_name" {
    description = "The domain name for the Route53 record (e.g., example.com or www.example.com)"
  type = string
}

variable "cf_domain" {
    description = "The domain name for the CloudFront distribution (e.g., example.com or www.example.com)"
  type = string
}

variable "cf_hosted_zone_id" {
    description = "The hosted zone ID for the CloudFront distribution"
  type = string
}




# The variable blocks you provided are Terraform variable declarations. 
# They define input parameters that users of the Terraform configuration can customize without altering the code. 
# Here is a breakdown of each variable, including its purpose, type, and typical usage in the context of a
# CloudFront and Route 53 setup on AWS.

# variable "domain_name"
# Purpose: This is the custom, user-facing domain name for your website
# (e.g., example.com or www.example.com). It is the domain you want to use for the DNS record that
# points to your CloudFront distribution.
# Type: string. This specifies that the input must be a text value, which is appropriate 
# for a domain name.
# Usage: The value of this variable is typically used in a DNS service like AWS Route 53 to create
# an ALIAS record. This record maps your friendly domain name to the underlying, automatically 
# generated CloudFront domain name, making your website publicly accessible via your custom domain. 

# variable "cf_domain"
# Purpose: This variable is intended to hold the domain name that is automatically
# generated by AWS when a CloudFront distribution is created (e.g., d111111abcdef8.cloudfront.net).
# This is a reference value that comes from the output of the CloudFront resource, not an input from the user.
# Type: string.
# Usage: In a well-structured Terraform configuration, this variable would not be declared as an input 
# but rather as an output variable that captures the value of the aws_cloudfront_distribution.this.domain_name attribute. 
# The description you included suggests it is being used to pass this value to another part of the 
#configuration, perhaps for creating the DNS record.. 

# variable "cf_hosted_zone_id"
# Purpose: This variable stores the special canonical hosted zone ID associated with the CloudFront 
# distribution. This ID is a crucial piece of information needed to configure DNS correctly.
# Type: string.
# Usage: Similar to cf_domain, this is typically an output value from the CloudFront resource.
# It is used in combination with the domain_name and cf_domain to create an ALIAS record in Route 53. 
# The ALIAS record needs this hosted zone ID to properly resolve your custom domain to the CloudFront distribution.. 
