#YAML file to deploy website to S3 using GitHub Actions
name: Deploy Website to S3
# Trigger the workflow on push to main branch
on:
  workflow_dispatch: # Run manually from GitHub Actions tab
    
# Define the job to run
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: www.ojes.online
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: ./2135_mini_finance  # path to your website files