#YAML file to destroy Terraform-managed infrastructure using GitHub Actions
name: Terraform Destroy
# Trigger the workflow manually
on:
  workflow_dispatch: # Run manually from GitHub Actions tab
# Define the job to run
jobs:
  terraform_destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
# Set environment variables for AWS credentials
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1 # update if different
# Define the steps to execute
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve